//----------------------
// <auto-generated>
//     Generated using the NSwag toolchain v14.1.0.0 (NJsonSchema v11.0.2.0 (Newtonsoft.Json v13.0.0.0)) (http://NSwag.org)
// </auto-generated>
//----------------------

/* tslint:disable */
/* eslint-disable */
// ReSharper disable InconsistentNaming

import moment from 'moment';


export interface Access {
    id?: number;
    isActive?: boolean;
    isDeleted?: boolean;
    createdBy?: string | undefined;
    createdDate?: moment.Moment;
    modifiedBy?: string | undefined;
    modifiedDate?: moment.Moment | undefined;
    moduleId?: number;
    module?: Module;
    roleAccesses?: RoleAccess[] | undefined;
}

export interface AccessType {
    id?: number;
    isActive?: boolean;
    isDeleted?: boolean;
    createdBy?: string | undefined;
    createdDate?: moment.Moment;
    modifiedBy?: string | undefined;
    modifiedDate?: moment.Moment | undefined;
    name?: string | undefined;
    code?: string | undefined;
    description?: string | undefined;
    sortOrder?: number;
}

export interface AgingBalanceReportDTO {
    customerId?: number;
    accountNumber?: number;
    customerName?: string | undefined;
    paymentTermId?: number;
    paymentTermName?: string | undefined;
    state?: string | undefined;
    phoneNumber?: string | undefined;
    email?: string | undefined;
    current30Days?: number | undefined;
    over30Days?: number | undefined;
    over60Days?: number | undefined;
    over90Days?: number | undefined;
    totalOwed?: number | undefined;
    lastPaymentDate?: moment.Moment | undefined;
    lastUpdateDate?: moment.Moment | undefined;
}

export interface Automobile {
    id?: number;
    isActive?: boolean;
    isDeleted?: boolean;
    createdBy?: string | undefined;
    createdDate?: moment.Moment;
    modifiedBy?: string | undefined;
    modifiedDate?: moment.Moment | undefined;
    name?: string | undefined;
    make?: string | undefined;
    model?: string | undefined;
    type?: string | undefined;
    year?: number;
    notes?: string | undefined;
}

export interface Category {
    id?: number;
    isActive?: boolean;
    isDeleted?: boolean;
    createdBy?: string | undefined;
    createdDate?: moment.Moment;
    modifiedBy?: string | undefined;
    modifiedDate?: moment.Moment | undefined;
    catId?: string | undefined;
    description?: string | undefined;
    type?: number | undefined;
    ebayId?: number | undefined;
    groupTitle?: string | undefined;
    groupLine?: number | undefined;
    classId?: string | undefined;
    est?: string | undefined;
    sequences?: Sequence[] | undefined;
}

export interface CategoryDTO {
    id?: number;
    catId?: string | undefined;
    description?: string | undefined;
}

export interface CheckInventoryRequest {
    parts?: PartInquiry[] | undefined;
    transactionDate?: moment.Moment;
}

export interface CheckInventoryResponse {
    parts?: PartInquiry[] | undefined;
    transactionDate?: moment.Moment;
}

export interface Contact {
    id?: number;
    isActive?: boolean;
    isDeleted?: boolean;
    createdBy?: string | undefined;
    createdDate?: moment.Moment;
    modifiedBy?: string | undefined;
    modifiedDate?: moment.Moment | undefined;
    customerId?: number;
    customer?: Customer;
    locationId?: number | undefined;
    location?: Location;
    positionTypeId?: number | undefined;
    positionType?: PositionType;
    contactName?: string | undefined;
    phoneNumber?: string | undefined;
    email?: string | undefined;
    notes?: string | undefined;
    isEmailOrder?: boolean;
    isEmailCreditMemo?: boolean;
    isEmailStatement?: boolean;
}

export interface CreateOrderResult {
    order?: Order;
    orderNumber?: number | undefined;
    quoteNumber?: number | undefined;
    orderResult?: boolean;
    syncResult?: boolean | undefined;
    isQuote?: boolean;
}

export interface Customer {
    id?: number;
    isActive?: boolean;
    isDeleted?: boolean;
    createdBy?: string | undefined;
    createdDate?: moment.Moment;
    modifiedBy?: string | undefined;
    modifiedDate?: moment.Moment | undefined;
    addressLine1?: string | undefined;
    addressLine2?: string | undefined;
    city?: string | undefined;
    state?: string | undefined;
    country?: string | undefined;
    zipCode?: string | undefined;
    phoneNumber?: string | undefined;
    faxNumber?: string | undefined;
    email?: string | undefined;
    latitude?: string | undefined;
    longitude?: string | undefined;
    accountNumber?: number;
    customerName?: string | undefined;
    customerTypeId?: number;
    customerType?: CustomerType;
    priceLevelId?: number | undefined;
    priceLevel?: PriceLevel;
    paymentTermId?: number | undefined;
    paymentTerm?: PaymentTerm;
    salesRepresentativeOutId?: number | undefined;
    salesRepresentativeOut?: SalesRepresentative;
    salesRepresentativeInId?: number | undefined;
    salesRepresentativeIn?: SalesRepresentative;
    defaultWarehouseId?: number | undefined;
    warehouse?: Warehouse;
    contactName?: string | undefined;
    taxRate?: number | undefined;
    overBalance?: number | undefined;
    creditLimit?: number | undefined;
    isBypassCreditLimit?: boolean;
    isTaxable?: boolean;
    isHoldAccount?: boolean;
    discount?: number | undefined;
    sellersPermit?: string | undefined;
    trialBalance?: number | undefined;
    accountsReceivableBalance?: number | undefined;
    crossStreet?: string | undefined;
    isWithShippingCost?: boolean;
    isWithHandlingCost?: boolean;
    isAllowViewCA?: boolean;
    isAllowViewVA?: boolean;
    isAllowViewWAG?: boolean;
    isOverrideCreditLimitRestriction?: boolean;
    shipperAccountNumber?: string | undefined;
    isApplyPFGShippingCharge?: boolean;
    isApplyPFGHandlingCharge?: boolean;
    isPFGShippingHandlingLevel?: boolean;
    freightPrepaidAmount?: number | undefined;
}

export interface CustomerCredit {
    id?: number;
    isActive?: boolean;
    isDeleted?: boolean;
    createdBy?: string | undefined;
    createdDate?: moment.Moment;
    modifiedBy?: string | undefined;
    modifiedDate?: moment.Moment | undefined;
    customerId?: number;
    customer?: Customer;
    referenceId?: number | undefined;
    creditType?: number;
    creditReason?: string | undefined;
    previousRecordId?: number;
    amountPostedDate?: moment.Moment;
    currentBalance?: number;
    previousBalance?: number;
    amountPosted?: number;
}

export interface CustomerDTO {
    id?: number;
    accountNumber?: number;
    customerName?: string | undefined;
    discount?: number | undefined;
    taxRate?: number | undefined;
    paymentTermId?: number | undefined;
    priceLevelId?: number | undefined;
    addressLine1?: string | undefined;
    addressLine2?: string | undefined;
    city?: string | undefined;
    state?: string | undefined;
    country?: string | undefined;
    zipCode?: string | undefined;
    zone?: string | undefined;
    contactName?: string | undefined;
    phoneNumber?: string | undefined;
    faxNumber?: string | undefined;
    email?: string | undefined;
    isHoldAccount?: boolean;
    creditLimit?: number;
    isBypassCreditLimit?: boolean;
    overBalance?: number;
    statementAmount?: number;
    contacts?: Contact[] | undefined;
    customerCredit?: CustomerCredit;
    locations?: Location[] | undefined;
}

export interface CustomerDTOPaginatedListDTO {
    recordCount?: number;
    data?: CustomerDTO[] | undefined;
}

export interface CustomerEmailDTO {
    customerId?: number;
    locationId?: number;
    positionTypeId?: number;
    contactName?: string | undefined;
    phoneNumber?: string | undefined;
    email?: string | undefined;
}

export interface CustomerNote {
    id?: number;
    isActive?: boolean;
    isDeleted?: boolean;
    createdBy?: string | undefined;
    createdDate?: moment.Moment;
    modifiedBy?: string | undefined;
    modifiedDate?: moment.Moment | undefined;
    customerId?: number;
    customer?: Customer;
    notes?: string | undefined;
    comment?: string | undefined;
}

export interface CustomerPaginatedListDTO {
    recordCount?: number;
    data?: Customer[] | undefined;
}

export interface CustomerSalesAmountDTO {
    customerId?: number;
    accountNumber?: number;
    customerName?: string | undefined;
    phoneNumber?: string | undefined;
    state?: string | undefined;
    column1?: SalesData;
    column2?: SalesData;
    column3?: SalesData;
    column4?: SalesData;
    column5?: SalesData;
    column6?: SalesData;
    column7?: SalesData;
    column8?: SalesData;
    column9?: SalesData;
    column10?: SalesData;
    column11?: SalesData;
    column12?: SalesData;
}

export interface CustomerSalesFilterDTO {
    col1FrDate?: moment.Moment | undefined;
    col1ToDate?: moment.Moment | undefined;
    col2FrDate?: moment.Moment | undefined;
    col2ToDate?: moment.Moment | undefined;
    col3FrDate?: moment.Moment | undefined;
    col3ToDate?: moment.Moment | undefined;
    col4FrDate?: moment.Moment | undefined;
    col4ToDate?: moment.Moment | undefined;
    col5FrDate?: moment.Moment | undefined;
    col5ToDate?: moment.Moment | undefined;
    col6FrDate?: moment.Moment | undefined;
    col6ToDate?: moment.Moment | undefined;
    col7FrDate?: moment.Moment | undefined;
    col7ToDate?: moment.Moment | undefined;
    col8FrDate?: moment.Moment | undefined;
    col8ToDate?: moment.Moment | undefined;
    col9FrDate?: moment.Moment | undefined;
    col9ToDate?: moment.Moment | undefined;
    col10FrDate?: moment.Moment | undefined;
    col10ToDate?: moment.Moment | undefined;
    col11FrDate?: moment.Moment | undefined;
    col11ToDate?: moment.Moment | undefined;
    col12FrDate?: moment.Moment | undefined;
    col12ToDate?: moment.Moment | undefined;
}

export interface CustomerType {
    id?: number;
    isActive?: boolean;
    isDeleted?: boolean;
    createdBy?: string | undefined;
    createdDate?: moment.Moment;
    modifiedBy?: string | undefined;
    modifiedDate?: moment.Moment | undefined;
    name?: string | undefined;
    code?: string | undefined;
    description?: string | undefined;
    sortOrder?: number;
}

export interface DailyPaymentSummaryDTO {
    caSummary?: TotalPaymentDTO;
    nvSummary?: TotalPaymentDTO;
}

export interface DailySalesSummaryDTO {
    caTotalProfitMargin?: number;
    caTotalReturnPercentage?: number;
    nvTotalProfitMargin?: number;
    nvTotalReturnPercentage?: number;
    caSummary?: TotalSalesDTO[] | undefined;
    nvSummary?: TotalSalesDTO[] | undefined;
}

export interface DailyVendorSalesSummaryDTO {
    vendorSummary?: TotalVendorSalesDTO[] | undefined;
}

export interface DeliverySummaryCA {
    numberOfStops?: number;
    zoneSummaries?: ZoneSummary[] | undefined;
}

export interface DeliverySummaryDTO {
    deliveryDate?: moment.Moment;
    deliverySummaryCA?: DeliverySummaryCA;
    deliverySummaryNV?: DeliverySummaryNV;
}

export interface DeliverySummaryNV {
    numberOfStops?: number;
    zoneSummaries?: ZoneSummary[] | undefined;
}

export interface Driver {
    id?: number;
    isActive?: boolean;
    isDeleted?: boolean;
    createdBy?: string | undefined;
    createdDate?: moment.Moment;
    modifiedBy?: string | undefined;
    modifiedDate?: moment.Moment | undefined;
    driverNumber?: number;
    driverNumberString?: string | undefined;
    firstName?: string | undefined;
    lastName?: string | undefined;
    phoneNumber?: string | undefined;
}

export interface DriverLog {
    id?: number;
    isActive?: boolean;
    isDeleted?: boolean;
    createdBy?: string | undefined;
    createdDate?: moment.Moment;
    modifiedBy?: string | undefined;
    modifiedDate?: moment.Moment | undefined;
    driverId?: number;
    driver?: Driver;
    driverName?: string | undefined;
    driverLogNumber?: string | undefined;
    statusId?: number;
    statusDetail?: string | undefined;
    driverLogDetails?: DriverLogDetail[] | undefined;
}

export interface DriverLogDetail {
    id?: number;
    isActive?: boolean;
    isDeleted?: boolean;
    createdBy?: string | undefined;
    createdDate?: moment.Moment;
    modifiedBy?: string | undefined;
    modifiedDate?: moment.Moment | undefined;
    driverLogId?: number;
    driverLog?: DriverLog;
    orderId?: number;
    orderNumber?: number;
    order?: Order;
    orderDetailId?: number;
    orderDetail?: OrderDetail;
    shipAddressName?: string | undefined;
    orderQuantity?: number;
    partNumber?: string | undefined;
    paymentTermName?: string | undefined;
    totalAmount?: number;
    statusId?: number;
    statusDetail?: string | undefined;
    orderTotalAmount?: number;
}

export interface DriverLogPaginatedListDTO {
    recordCount?: number;
    data?: DriverLog[] | undefined;
}

export interface ItemMasterlistReference {
    id?: number;
    isActive?: boolean;
    isDeleted?: boolean;
    createdBy?: string | undefined;
    createdDate?: moment.Moment;
    modifiedBy?: string | undefined;
    modifiedDate?: moment.Moment | undefined;
    productId?: number;
    product?: Product;
    partNumber?: string | undefined;
    partsLinkNumber?: string | undefined;
    oemNumber?: string | undefined;
    isMainPartsLink?: boolean;
    isMainOEM?: boolean;
}

export interface Location {
    id?: number;
    isActive?: boolean;
    isDeleted?: boolean;
    createdBy?: string | undefined;
    createdDate?: moment.Moment;
    modifiedBy?: string | undefined;
    modifiedDate?: moment.Moment | undefined;
    addressLine1?: string | undefined;
    addressLine2?: string | undefined;
    city?: string | undefined;
    state?: string | undefined;
    country?: string | undefined;
    zipCode?: string | undefined;
    phoneNumber?: string | undefined;
    faxNumber?: string | undefined;
    email?: string | undefined;
    latitude?: string | undefined;
    longitude?: string | undefined;
    customerId?: number;
    customer?: Customer;
    locationTypeId?: number;
    locationType?: LocationType;
    locationName?: string | undefined;
    locationCode?: string | undefined;
    notes?: string | undefined;
    zone?: string | undefined;
}

export interface LocationDTO {
    id?: number;
    customerId?: number;
    locationTypeId?: number;
    locationName?: string | undefined;
    locationCode?: string | undefined;
    isDeleted?: boolean;
    addressLine1?: string | undefined;
    addressLine2?: string | undefined;
    city?: string | undefined;
    state?: string | undefined;
    country?: string | undefined;
    zipCode?: string | undefined;
    zone?: string | undefined;
    contactName?: string | undefined;
    phoneNumber?: string | undefined;
    faxNumber?: string | undefined;
    email?: string | undefined;
}

export interface LocationType {
    id?: number;
    isActive?: boolean;
    isDeleted?: boolean;
    createdBy?: string | undefined;
    createdDate?: moment.Moment;
    modifiedBy?: string | undefined;
    modifiedDate?: moment.Moment | undefined;
    name?: string | undefined;
    code?: string | undefined;
    description?: string | undefined;
    sortOrder?: number;
}

export interface LoginDTO {
    email?: string | undefined;
    password?: string | undefined;
}

export interface LoginResponse {
    status?: number;
    message?: string | undefined;
    token?: string | undefined;
    user?: User;
}

export interface MakeDTO {
    make?: string | undefined;
}

export interface ModelDTO {
    model?: string | undefined;
}

export interface Module {
    id?: number;
    isActive?: boolean;
    isDeleted?: boolean;
    createdBy?: string | undefined;
    createdDate?: moment.Moment;
    modifiedBy?: string | undefined;
    modifiedDate?: moment.Moment | undefined;
    name?: string | undefined;
    code?: string | undefined;
    description?: string | undefined;
    sortOrder?: number;
    moduleGroupId?: number;
    moduleGroup?: ModuleGroup;
    accessTypeId?: number | undefined;
}

export interface ModuleGroup {
    id?: number;
    isActive?: boolean;
    isDeleted?: boolean;
    createdBy?: string | undefined;
    createdDate?: moment.Moment;
    modifiedBy?: string | undefined;
    modifiedDate?: moment.Moment | undefined;
    name?: string | undefined;
    code?: string | undefined;
    description?: string | undefined;
    sortOrder?: number;
    modules?: Module[] | undefined;
}

export interface Order {
    id?: number;
    isActive?: boolean;
    isDeleted?: boolean;
    createdBy?: string | undefined;
    createdDate?: moment.Moment;
    modifiedBy?: string | undefined;
    modifiedDate?: moment.Moment | undefined;
    customerId?: number;
    customer?: Customer;
    paymentTermId?: number | undefined;
    paymentTerm?: PaymentTerm;
    warehouseId?: number;
    warehouse?: Warehouse;
    orderNumber?: number | undefined;
    quoteNumber?: number | undefined;
    customerName?: string | undefined;
    accountNumber?: number;
    paymentTermName?: string | undefined;
    priceLevelId?: number;
    priceLevelName?: string | undefined;
    warehouseName?: string | undefined;
    orderDate?: moment.Moment;
    user?: string | undefined;
    orderStatusId?: number;
    orderStatusName?: string | undefined;
    orderedBy?: string | undefined;
    orderedByEmail?: string | undefined;
    orderedByPhoneNumber?: string | undefined;
    orderedByNotes?: string | undefined;
    deliveryType?: number;
    deliveryDate?: moment.Moment;
    deliveryRoute?: number | undefined;
    discount?: number | undefined;
    restockingFee?: number | undefined;
    restockingAmount?: number | undefined;
    taxRate?: number | undefined;
    totalTax?: number | undefined;
    subTotalAmount?: number | undefined;
    totalAmount?: number | undefined;
    isQuote?: boolean;
    isPrinted?: boolean;
    isCustomerOrder?: boolean;
    linkedInvoiceNumber?: string | undefined;
    orderDetails?: OrderDetail[] | undefined;
    email?: string | undefined;
    phoneNumber?: string | undefined;
    billAddress?: string | undefined;
    billCity?: string | undefined;
    billState?: string | undefined;
    billZipCode?: string | undefined;
    billZone?: string | undefined;
    billPhoneNumber?: string | undefined;
    billContactName?: string | undefined;
    shipAddressName?: string | undefined;
    shipAddress?: string | undefined;
    shipCity?: string | undefined;
    shipState?: string | undefined;
    shipZipCode?: string | undefined;
    shipZone?: string | undefined;
    shipPhoneNumber?: string | undefined;
    shipContactName?: string | undefined;
    isHoldInvoice?: boolean;
    invoiceNumber?: number | undefined;
    fwd?: number | undefined;
    originalInvoiceNumber?: number | undefined;
    orderType?: number | undefined;
    handlingType?: number | undefined;
    creditType?: number | undefined;
    singleInvoice?: number | undefined;
    purchaseOrderNumber?: string | undefined;
    type?: string | undefined;
    category?: string | undefined;
    carrier?: string | undefined;
    trackingNumber?: string | undefined;
    salesRepresentative1?: string | undefined;
    salesRepresentative2?: string | undefined;
    invoiceNotes?: string | undefined;
    particular?: string | undefined;
    paymentReference?: string | undefined;
    postedBy?: string | undefined;
    accountingPaidBy?: string | undefined;
    transactionDate?: moment.Moment | undefined;
    postDate?: moment.Moment | undefined;
    paymentDate?: moment.Moment | undefined;
    debit?: number | undefined;
    credit?: number | undefined;
    quantity?: number | undefined;
    quantityShipped?: number | undefined;
    currentCost?: number | undefined;
    amountPaid?: number | undefined;
    balance?: number | undefined;
    payment?: number | undefined;
    listPrice?: number | undefined;
    rgaType?: number;
    rgaReason?: number;
    rgaReasonNotes?: string | undefined;
}

export interface OrderDetail {
    id?: number;
    isActive?: boolean;
    isDeleted?: boolean;
    createdBy?: string | undefined;
    createdDate?: moment.Moment;
    modifiedBy?: string | undefined;
    modifiedDate?: moment.Moment | undefined;
    orderId?: number;
    order?: Order;
    productId?: number;
    product?: Product;
    categoryId?: number;
    orderQuantity?: number;
    onHandQuantity?: number | undefined;
    location?: string | undefined;
    warehouseLocationId?: number | undefined;
    partNumber?: string | undefined;
    partDescription?: string | undefined;
    brand?: string | undefined;
    mainPartsLinkNumber?: string | undefined;
    mainOEMNumber?: string | undefined;
    vendorCode?: string | undefined;
    vendorPartNumber?: string | undefined;
    vendorPrice?: number;
    vendorOnHand?: number;
    yearFrom?: number;
    yearTo?: number;
    listPrice?: number;
    wholesalePrice?: number;
    discountedPrice?: number;
    totalAmount?: number;
    restockingFee?: number | undefined;
    restockingAmount?: number | undefined;
    discount?: number;
    discountAmount?: number;
    discountRecord?: number;
    discountRecordAmount?: number;
    partsLinks?: string | undefined;
    oeMs?: string | undefined;
    vendorCodes?: string | undefined;
    imageUrl?: string | undefined;
    stocks?: WarehouseStock[] | undefined;
    vendorCatalogs?: VendorCatalog[] | undefined;
    warehouseTrackings?: WarehouseTracking[] | undefined;
    vehicle?: string | undefined;
    salesRepresentative?: string | undefined;
    warehouseLocation?: string | undefined;
    vendorInfo?: string | undefined;
    warehouseTracking?: string | undefined;
    carrier?: string | undefined;
    trackingNumber?: string | undefined;
    salesOrderNumber?: number | undefined;
    originalInvoiceNumber?: number | undefined;
    buyOutOrder?: number | undefined;
    partSize?: number | undefined;
    statusId?: number | undefined;
    shippedQuantity?: number | undefined;
    scannedQuantity?: number | undefined;
    pickedQuantity?: number | undefined;
    returnQuantity?: number | undefined;
    remainingQuantity?: number | undefined;
    itemCatalog?: number | undefined;
    toShip?: number | undefined;
    price?: number | undefined;
    unitCost?: number | undefined;
    shipCharge?: number | undefined;
    shipDate?: moment.Moment | undefined;
    rgaInspectedCode?: number | undefined;
    rgaState?: number | undefined;
    rgaLocation?: string | undefined;
    rgaPartNumber?: string | undefined;
    isCreditMemoCreated?: boolean;
}

export interface OrderInfo {
    order?: PlaceOrder;
    parts?: PlacePart[] | undefined;
}

export interface OrderNote {
    id?: number;
    isActive?: boolean;
    isDeleted?: boolean;
    createdBy?: string | undefined;
    createdDate?: moment.Moment;
    modifiedBy?: string | undefined;
    modifiedDate?: moment.Moment | undefined;
    orderId?: number;
    order?: Order;
    notes?: string | undefined;
}

export interface OrderPaginatedListDTO {
    recordCount?: number;
    data?: Order[] | undefined;
}

export interface OrderStatusRequest {
    orders?: StatusOrder[] | undefined;
    transactionDate?: moment.Moment;
}

export interface OrderStatusResponse {
    orders?: StatusOrderParts[] | undefined;
    transactionDate?: moment.Moment;
}

export interface OverpaymentParameterDTO {
    customerId?: number;
    amount?: number;
    userName?: string | undefined;
    notes?: string | undefined;
}

export interface PartInquiry {
    orderItemId?: number;
    sku?: string | undefined;
    brand?: string | undefined;
    quantity?: number;
    stock?: number | undefined;
    vendorPrice?: number;
    vendorCorePrice?: number | undefined;
    shipCharge?: number | undefined;
    isSpecial?: boolean;
    remarks?: string | undefined;
}

export interface PartsCatalog {
    id?: number;
    isActive?: boolean;
    isDeleted?: boolean;
    createdBy?: string | undefined;
    createdDate?: moment.Moment;
    modifiedBy?: string | undefined;
    modifiedDate?: moment.Moment | undefined;
    partNumber?: string | undefined;
    productId?: number | undefined;
    product?: Product;
    make?: string | undefined;
    model?: string | undefined;
    yearFrom?: number;
    yearTo?: number;
    cylinder?: number;
    liter?: number;
    groupHead?: string | undefined;
    subGroup?: string | undefined;
    subModel?: string | undefined;
    position?: string | undefined;
    brand?: string | undefined;
    notes?: string | undefined;
}

export interface PartsManifest {
    id?: number;
    isActive?: boolean;
    isDeleted?: boolean;
    createdBy?: string | undefined;
    createdDate?: moment.Moment;
    modifiedBy?: string | undefined;
    modifiedDate?: moment.Moment | undefined;
    driverId?: number;
    driver?: Driver;
    driverName?: string | undefined;
    partsManifestNumber?: string | undefined;
    purposeId?: number;
    purposeName?: string | undefined;
    vendorId?: number | undefined;
    vendorCode?: string | undefined;
    vendorName?: string | undefined;
    partsManifestDetails?: PartsManifestDetail[] | undefined;
}

export interface PartsManifestDetail {
    id?: number;
    isActive?: boolean;
    isDeleted?: boolean;
    createdBy?: string | undefined;
    createdDate?: moment.Moment;
    modifiedBy?: string | undefined;
    modifiedDate?: moment.Moment | undefined;
    partsManifestId?: number;
    partsManifest?: PartsManifest;
    productId?: number;
    partNumber?: string | undefined;
    partDescription?: string | undefined;
    product?: Product;
    quantity?: number;
}

export interface PartsManifestPaginatedListDTO {
    recordCount?: number;
    data?: PartsManifest[] | undefined;
}

export interface PartsPicking {
    id?: number;
    isActive?: boolean;
    isDeleted?: boolean;
    createdBy?: string | undefined;
    createdDate?: moment.Moment;
    modifiedBy?: string | undefined;
    modifiedDate?: moment.Moment | undefined;
    pickNumber?: string | undefined;
    statusId?: number;
    pickStatus?: string | undefined;
    partsPickingDate?: moment.Moment;
    isPrinted?: boolean;
    partsPickingDetails?: PartsPickingDetail[] | undefined;
}

export interface PartsPickingDetail {
    id?: number;
    isActive?: boolean;
    isDeleted?: boolean;
    createdBy?: string | undefined;
    createdDate?: moment.Moment;
    modifiedBy?: string | undefined;
    modifiedDate?: moment.Moment | undefined;
    partsPickingId?: number;
    partsPicking?: PartsPicking;
    orderDetailId?: number;
    orderDetail?: OrderDetail;
    productId?: number;
    product?: Product;
    orderId?: number;
    orderNumber?: number;
    orderQuantity?: number;
    stockQuantity?: number;
    stockLocation?: string | undefined;
    shipZone?: string | undefined;
    partNumber?: string | undefined;
    sequence?: string | undefined;
    partDescription?: string | undefined;
    orderDate?: moment.Moment;
    deliveryDate?: moment.Moment;
    deliveryRoute?: number;
    statusId?: number;
    ppDetailStatus?: string | undefined;
    deliveryMethod?: string | undefined;
    mainPartsLinkNumber?: string | undefined;
    purchaseOrderNumber?: string | undefined;
    customerName?: string | undefined;
    warehouseLocations?: WarehousePartDTO[] | undefined;
}

export interface PartsPickingPaginatedListDTO {
    recordCount?: number;
    data?: PartsPicking[] | undefined;
}

export interface Payment {
    id?: number;
    isActive?: boolean;
    isDeleted?: boolean;
    createdBy?: string | undefined;
    createdDate?: moment.Moment;
    modifiedBy?: string | undefined;
    modifiedDate?: moment.Moment | undefined;
    customerId?: number;
    customer?: Customer;
    accountNumber?: number;
    salesRepresentativeId?: number | undefined;
    paymentDate?: moment.Moment | undefined;
    totalAmountDue?: number | undefined;
    paymentAmount?: number | undefined;
    paymentBalance?: number | undefined;
    paymentType?: string | undefined;
    referenceNumber?: string | undefined;
    appliesTo?: string | undefined;
    linkedInvoiceNumber?: string | undefined;
    isReversePayment?: boolean;
    isUseCustomerCredit?: boolean;
    customerCreditId?: number | undefined;
    customerCredit?: CustomerCredit;
    customerCreditAmountUsed?: number | undefined;
    purchaseOrderNumber?: string | undefined;
    oti?: string | undefined;
    lockedBy?: string | undefined;
    lockeddate?: moment.Moment;
    currencyCode?: string | undefined;
    exchangeDifference?: number | undefined;
    invoiceRate?: number | undefined;
    paymentCurrencyCode?: string | undefined;
    paymentRate?: number | undefined;
    deposit?: string | undefined;
    checkStatus?: string | undefined;
    particular?: string | undefined;
    phone?: string | undefined;
    notes?: string | undefined;
    paymentDetails?: PaymentDetail[] | undefined;
    creditMemos?: Order[] | undefined;
}

export interface PaymentDetail {
    id?: number;
    isActive?: boolean;
    isDeleted?: boolean;
    createdBy?: string | undefined;
    createdDate?: moment.Moment;
    modifiedBy?: string | undefined;
    modifiedDate?: moment.Moment | undefined;
    paymentId?: number;
    payment?: Payment;
    orderNumber?: number;
    invoiceNumber?: number;
    invoiceAmount?: number;
    paymentAmount?: number;
    invoiceBalance?: number;
    customerCreditAmountUsed?: number | undefined;
    linkedInvoiceNumber?: string | undefined;
}

export interface PaymentHistoryDTO {
    id?: number;
    paymentDate?: moment.Moment;
    totalAmountDue?: number;
    paymentAmount?: number;
    paymentBalance?: number;
    customerCreditAmountUsed?: number;
    paymentType?: string | undefined;
    referenceNumber?: string | undefined;
    invoiceAmount?: number;
    invoicePaymentAmount?: number;
    invoiceBalance?: number;
    linkedInvoiceNumber?: string | undefined;
}

export interface PaymentPaginatedListDTO {
    recordCount?: number;
    data?: Payment[] | undefined;
}

export interface PaymentTerm {
    id?: number;
    isActive?: boolean;
    isDeleted?: boolean;
    createdBy?: string | undefined;
    createdDate?: moment.Moment;
    modifiedBy?: string | undefined;
    modifiedDate?: moment.Moment | undefined;
    termName?: string | undefined;
    description?: string | undefined;
    numberOfDays?: number;
    notes?: string | undefined;
}

export interface PaymentType {
    id?: number;
    isActive?: boolean;
    isDeleted?: boolean;
    createdBy?: string | undefined;
    createdDate?: moment.Moment;
    modifiedBy?: string | undefined;
    modifiedDate?: moment.Moment | undefined;
    name?: string | undefined;
    code?: string | undefined;
    description?: string | undefined;
    sortOrder?: number;
}

export interface PlaceOrder {
    vendedId?: string | undefined;
    deliveryName?: string | undefined;
    deliveryStreet?: string | undefined;
    deliverySuburb?: string | undefined;
    deliveryCity?: string | undefined;
    deliveryState?: string | undefined;
    deliveryTelephone?: string | undefined;
    deliveryPostCode?: string | undefined;
    customerEmail?: string | undefined;
    supplierOrderId?: number | undefined;
    carrier?: string | undefined;
    channel?: string | undefined;
    comments?: string | undefined;
    shippingMethod?: string | undefined;
    wosCustomerId?: number | undefined;
    shipperAccountNumber?: number | undefined;
    crossReferencePO?: string | undefined;
    estFreight?: number;
    anError?: string | undefined;
    soNumber?: number | undefined;
}

export interface PlaceOrderRequest {
    orderInfos?: OrderInfo[] | undefined;
    transactionDate?: moment.Moment;
}

export interface PlaceOrderResponse {
    orderInfos?: OrderInfo[] | undefined;
    transactionDate?: moment.Moment;
}

export interface PlacePart {
    orderItemId?: number;
    warrantyItemID?: number | undefined;
    sku?: string | undefined;
    brand?: string | undefined;
    partName?: string | undefined;
    quantity?: number;
    stock?: number | undefined;
    vendorPrice?: number | undefined;
    vendorCorePrice?: number | undefined;
    shipCharge?: number | undefined;
    listPrice?: number;
    crossReference?: string | undefined;
    isSpecial?: boolean | undefined;
    status?: string | undefined;
}

export interface PositionType {
    id?: number;
    isActive?: boolean;
    isDeleted?: boolean;
    createdBy?: string | undefined;
    createdDate?: moment.Moment;
    modifiedBy?: string | undefined;
    modifiedDate?: moment.Moment | undefined;
    name?: string | undefined;
    code?: string | undefined;
    description?: string | undefined;
    sortOrder?: number;
}

export interface PriceLevel {
    id?: number;
    isActive?: boolean;
    isDeleted?: boolean;
    createdBy?: string | undefined;
    createdDate?: moment.Moment;
    modifiedBy?: string | undefined;
    modifiedDate?: moment.Moment | undefined;
    levelName?: string | undefined;
    description?: string | undefined;
    amount?: number;
    markUp?: number | undefined;
    notes?: string | undefined;
}

export interface Product {
    id?: number;
    isActive?: boolean;
    isDeleted?: boolean;
    createdBy?: string | undefined;
    createdDate?: moment.Moment;
    modifiedBy?: string | undefined;
    modifiedDate?: moment.Moment | undefined;
    partNumber?: string | undefined;
    originalPartNumber?: string | undefined;
    partDescription?: string | undefined;
    brand?: string | undefined;
    priceLevel1?: number | undefined;
    priceLevel2?: number | undefined;
    priceLevel3?: number | undefined;
    priceLevel4?: number | undefined;
    priceLevel5?: number | undefined;
    priceLevel6?: number | undefined;
    priceLevel7?: number | undefined;
    priceLevel8?: number | undefined;
    previousCost?: number | undefined;
    currentCost?: number | undefined;
    oemListPrice?: number | undefined;
    imageUrl?: string | undefined;
    image?: string | undefined;
    categoryId?: number | undefined;
    sequenceId?: number | undefined;
    statusId?: number | undefined;
    partSizeId?: number | undefined;
    dateAdded?: moment.Moment | undefined;
    onReceivingHold?: number | undefined;
    onOrder?: number | undefined;
    isDropShipAllowed?: boolean | undefined;
    isWebsiteOption?: boolean | undefined;
    isCAProduct?: boolean;
    isNVProduct?: boolean;
    isAPIAllowed?: boolean;
    partsLinkNumber?: string | undefined;
    oemNumber?: string | undefined;
    partsLinkList?: ItemMasterlistReference[] | undefined;
    readonly partsLinks?: string | undefined;
    readonly oeMs?: string | undefined;
    vendorCatalogList?: VendorCatalog[] | undefined;
    readonly vendorCodes?: string | undefined;
    readonly vendorPartNumbers?: string | undefined;
    yearFrom?: number;
    yearTo?: number;
    copyType?: string | undefined;
    stockQuantity?: number | undefined;
}

export interface ProductDTO {
    id?: number;
    partNumber?: string | undefined;
    partDescription?: string | undefined;
    brand?: string | undefined;
    categoryId?: number | undefined;
    sequenceId?: number | undefined;
    statusId?: number | undefined;
    partSizeId?: number | undefined;
    partsLinks?: string | undefined;
    oeMs?: string | undefined;
    vendorCodes?: string | undefined;
    partsLinkNumber?: string | undefined;
    oemNumber?: string | undefined;
    yearFrom?: number;
    yearTo?: number;
    listPrice?: number | undefined;
    priceLevel1?: number | undefined;
    priceLevel2?: number | undefined;
    priceLevel3?: number | undefined;
    priceLevel4?: number | undefined;
    priceLevel5?: number | undefined;
    priceLevel6?: number | undefined;
    priceLevel7?: number | undefined;
    priceLevel8?: number | undefined;
    stock?: number;
    currentCost?: number;
    stocks?: WarehouseStock[] | undefined;
    vendorCatalogs?: VendorCatalog[] | undefined;
}

export interface ProductDTOPaginatedListDTO {
    recordCount?: number;
    data?: ProductDTO[] | undefined;
}

export interface ProductFilterDTO {
    state?: number;
    year?: number | undefined;
    categoryIds?: number[] | undefined;
    sequenceIds?: number[] | undefined;
    make?: string | undefined;
    model?: string | undefined;
    isCAProduct?: boolean;
    isNVProduct?: boolean;
}

export interface ProductListDTO {
    id?: number;
    partNumber?: string | undefined;
    partDescription?: string | undefined;
    imageUrl?: string | undefined;
    yearFrom?: number;
    yearTo?: number;
    isActive?: boolean;
    isCAProduct?: boolean;
    isNVProduct?: boolean;
}

export interface ProductListDTOPaginatedListDTO {
    recordCount?: number;
    data?: ProductListDTO[] | undefined;
}

export interface ProductPaginatedListDTO {
    recordCount?: number;
    data?: Product[] | undefined;
}

export interface ProductVendorCatalog {
    vendorCatalog?: VendorCatalog;
    partsLinkNumbers?: string[] | undefined;
}

export interface PurchaseOrder {
    id?: number;
    isActive?: boolean;
    isDeleted?: boolean;
    createdBy?: string | undefined;
    createdDate?: moment.Moment;
    modifiedBy?: string | undefined;
    modifiedDate?: moment.Moment | undefined;
    vendorId?: number;
    vendor?: Vendor;
    vendorName?: string | undefined;
    vendorCode?: string | undefined;
    vendorPO?: string | undefined;
    pfwbNumber?: string | undefined;
    statusId?: number;
    poStatus?: string | undefined;
    purchaseOrderDate?: moment.Moment;
    receivedDate?: moment.Moment | undefined;
    isPrinted?: boolean;
    totalQuantity?: number;
    totalAmount?: number;
    purchaseOrderDetails?: PurchaseOrderDetail[] | undefined;
}

export interface PurchaseOrderDetail {
    id?: number;
    isActive?: boolean;
    isDeleted?: boolean;
    createdBy?: string | undefined;
    createdDate?: moment.Moment;
    modifiedBy?: string | undefined;
    modifiedDate?: moment.Moment | undefined;
    purchaseOrderId?: number;
    purchaseOrder?: PurchaseOrder;
    orderDetailId?: number;
    orderDetail?: OrderDetail;
    orderId?: number;
    orderNumber?: number;
    orderQuantity?: number;
    shipZone?: string | undefined;
    partNumber?: string | undefined;
    vendorPartNumber?: string | undefined;
    vendorPrice?: number;
    sequence?: string | undefined;
    partDescription?: string | undefined;
    orderDate?: moment.Moment;
    deliveryDate?: moment.Moment;
    deliveryRoute?: number;
    statusId?: number;
    poDetailStatus?: string | undefined;
    deliveryMethod?: string | undefined;
    mainPartsLinkNumber?: string | undefined;
    purchaseOrderNumber?: string | undefined;
    customerName?: string | undefined;
    receivedDate?: moment.Moment | undefined;
}

export interface PurchaseOrderPaginatedListDTO {
    recordCount?: number;
    data?: PurchaseOrder[] | undefined;
}

export interface RegisterUserDTO {
    accountNumber?: number;
    customerName?: string | undefined;
    locationName?: string | undefined;
    contactName?: string | undefined;
    addressLine1?: string | undefined;
    addressLine2?: string | undefined;
    city?: string | undefined;
    state?: string | undefined;
    country?: string | undefined;
    zipCode?: string | undefined;
    phoneNumber?: string | undefined;
    faxNumber?: string | undefined;
    userName?: string | undefined;
    email?: string | undefined;
    password?: string | undefined;
}

export interface RegistrationResponse {
    status?: number;
    message?: string | undefined;
    user?: User;
    users?: User[] | undefined;
}

export interface Role {
    id?: number;
    isActive?: boolean;
    isDeleted?: boolean;
    createdBy?: string | undefined;
    createdDate?: moment.Moment;
    modifiedBy?: string | undefined;
    modifiedDate?: moment.Moment | undefined;
    name?: string | undefined;
    code?: string | undefined;
    description?: string | undefined;
    sortOrder?: number;
    userTypeId?: number;
    userType?: UserType;
    notes?: string | undefined;
    rolePermissions?: RolePermission[] | undefined;
}

export interface RoleAccess {
    id?: number;
    isActive?: boolean;
    isDeleted?: boolean;
    createdBy?: string | undefined;
    createdDate?: moment.Moment;
    modifiedBy?: string | undefined;
    modifiedDate?: moment.Moment | undefined;
    roleId?: number;
    role?: Role;
    accessId?: number;
    access?: Access;
    accessType?: number;
}

export interface RoleModuleAccess {
    id?: number;
    isActive?: boolean;
    isDeleted?: boolean;
    createdBy?: string | undefined;
    createdDate?: moment.Moment;
    modifiedBy?: string | undefined;
    modifiedDate?: moment.Moment | undefined;
    roleId?: number;
    role?: Role;
    moduleId?: number;
    module?: Module;
    accessTypeId?: number;
    accessType?: AccessType;
}

export interface RolePermission {
    id?: number;
    isActive?: boolean;
    isDeleted?: boolean;
    createdBy?: string | undefined;
    createdDate?: moment.Moment;
    modifiedBy?: string | undefined;
    modifiedDate?: moment.Moment | undefined;
    roleId?: number;
    role?: Role;
    moduleGroupId?: number;
    moduleGroup?: ModuleGroup;
    moduleId?: number;
    module?: Module;
    accessTypeId?: number;
    accessType?: AccessType;
}

export interface SalesData {
    amount?: number | undefined;
    cost?: number | undefined;
    profit?: number | undefined;
    margin?: number | undefined;
}

export interface SalesRepresentative {
    id?: number;
    isActive?: boolean;
    isDeleted?: boolean;
    createdBy?: string | undefined;
    createdDate?: moment.Moment;
    modifiedBy?: string | undefined;
    modifiedDate?: moment.Moment | undefined;
    contactName?: string | undefined;
    phoneNumber?: string | undefined;
    email?: string | undefined;
    type?: number;
    notes?: string | undefined;
}

export interface Sequence {
    id?: number;
    isActive?: boolean;
    isDeleted?: boolean;
    createdBy?: string | undefined;
    createdDate?: moment.Moment;
    modifiedBy?: string | undefined;
    modifiedDate?: moment.Moment | undefined;
    categoryId?: number;
    category?: Category;
    catId?: string | undefined;
    categoryGroupDescription?: string | undefined;
    arrange?: number;
    name?: string | undefined;
    categoryDescription2?: string | undefined;
    estReference?: string | undefined;
    arr?: number | undefined;
}

export interface SequenceDTO {
    id?: number;
    categoryId?: number;
    catId?: string | undefined;
    categoryGroupDescription?: string | undefined;
}

export interface SessionTimeoutDTO {
    sessionTimeout?: number;
    dialogCountdown?: number;
}

export interface StatementEmailParamDTO {
    reportDate?: moment.Moment;
    dueDate?: moment.Moment;
    paymentTermId?: number;
    customerIds?: number[] | undefined;
}

export interface StatementReportDTO {
    customerId?: number;
    accountNumber?: number;
    totalDue?: number;
    customerName?: string | undefined;
    paymentTermId?: number;
    paymentTermName?: string | undefined;
    addressLine1?: string | undefined;
    addressLine2?: string | undefined;
    city?: string | undefined;
    state?: string | undefined;
    country?: string | undefined;
    zipCode?: string | undefined;
    phoneNumber?: string | undefined;
    orders?: StatementReportOrderDTO[] | undefined;
}

export interface StatementReportOrderDTO {
    orderId?: number;
    orderNumber?: number | undefined;
    invoiceNumber?: number | undefined;
    purchaseOrderNumber?: string | undefined;
    totalAmount?: number | undefined;
    balance?: number | undefined;
    orderDate?: moment.Moment;
    orderType?: string | undefined;
}

export interface StatementTotalReportDTO {
    customerId?: number;
    accountNumber?: number;
    totalDue?: number;
}

export interface StatusOrder {
    poNumber?: string | undefined;
    supplierId?: number;
}

export interface StatusOrderParts {
    poNumber?: string | undefined;
    supplierId?: number;
    status?: string | undefined;
    parts?: StatusPart[] | undefined;
}

export interface StatusPart {
    status?: string | undefined;
    tracking?: string | undefined;
    shipDate?: moment.Moment | undefined;
    carrier?: string | undefined;
    sku?: string | undefined;
    quantityOrdered?: number;
    quantityShipped?: number;
}

export interface StockOrderDetailDTO {
    id?: number;
    isActive?: boolean;
    isDeleted?: boolean;
    createdBy?: string | undefined;
    createdDate?: moment.Moment;
    modifiedBy?: string | undefined;
    modifiedDate?: moment.Moment | undefined;
    orderId?: number;
    orderDetailId?: number;
    productId?: number;
    orderNumber?: number;
    purchaseOrderNumber?: string | undefined;
    mainPartsLinkNumber?: string | undefined;
    deliveryMethod?: string | undefined;
    sequence?: string | undefined;
    orderQuantity?: number;
    shipZone?: string | undefined;
    partNumber?: string | undefined;
    stockQuantity?: number;
    stockLocation?: string | undefined;
    partDescription?: string | undefined;
    orderDate?: moment.Moment;
    poDetailStatus?: string | undefined;
    customerName?: string | undefined;
    deliveryDate?: moment.Moment;
    deliveryRoute?: number | undefined;
    warehouseLocations?: WarehousePartDTO[] | undefined;
}

export interface StockPartsLocation {
    id?: number;
    isActive?: boolean;
    isDeleted?: boolean;
    createdBy?: string | undefined;
    createdDate?: moment.Moment;
    modifiedBy?: string | undefined;
    modifiedDate?: moment.Moment | undefined;
    partNumber?: string | undefined;
    location?: string | undefined;
    area?: string | undefined;
    warehouseCode?: string | undefined;
    quantity?: number;
    status?: number | undefined;
    locationType?: number | undefined;
    pickable?: number | undefined;
    tag?: number | undefined;
    percentage?: number | undefined;
    transactionDate?: moment.Moment | undefined;
    accessDate?: moment.Moment | undefined;
}

export interface StockSettings {
    id?: number;
    isActive?: boolean;
    isDeleted?: boolean;
    createdBy?: string | undefined;
    createdDate?: moment.Moment;
    modifiedBy?: string | undefined;
    modifiedDate?: moment.Moment | undefined;
    isCaliforniaCAProduct?: boolean;
    isCaliforniaNVProduct?: boolean;
    isNevadaCAProduct?: boolean;
    isNevadaNVProduct?: boolean;
    isDropShipCAProduct?: boolean;
    isDropShipNVProduct?: boolean;
}

export interface TotalPaymentDTO {
    cashAmount?: number;
    checkAmount?: number;
    creditCardAmount?: number;
    achAmount?: number;
    writeOff?: number;
    creditMemoAmount?: number;
    totalAmount?: number;
}

export interface TotalSalesDTO {
    salesAmount?: number;
    creditAmount?: number;
    netSalesAmount?: number;
    unitCost?: number;
    profitMargin?: number;
    returnPercentage?: number;
    salesPerson?: string | undefined;
}

export interface TotalVendorSalesDTO {
    vendorName?: string | undefined;
    vendorCode?: string | undefined;
    salesAmount?: number;
    quantity?: number;
}

export interface User {
    id?: number;
    isActive?: boolean;
    isDeleted?: boolean;
    createdBy?: string | undefined;
    createdDate?: moment.Moment;
    modifiedBy?: string | undefined;
    modifiedDate?: moment.Moment | undefined;
    roleId?: number;
    role?: Role;
    customerId?: number | undefined;
    customer?: Customer;
    locationId?: number | undefined;
    location?: Location;
    userName?: string | undefined;
    email?: string | undefined;
    isCustomerUser?: boolean;
    isActivated?: boolean;
    isChangePasswordOnLogin?: boolean;
    passwordHash?: string | undefined;
    passwordSalt?: string | undefined;
}

export interface UserDTO {
    userName?: string | undefined;
    email?: string | undefined;
    roleId?: number;
    password?: string | undefined;
    isCustomerUser?: boolean;
    customerId?: number | undefined;
    locationId?: number | undefined;
    createdBy?: string | undefined;
    createdDate?: moment.Moment;
    isActive?: boolean;
    isActivated?: boolean;
    isChangePasswordOnLogin?: boolean;
}

export interface UserNotificationCreditNoteDTO {
    userId?: number;
    customerId?: number;
    customerName?: string | undefined;
    phoneNumber?: string | undefined;
    email?: string | undefined;
    creditMemoNumber?: number | undefined;
    amount?: number | undefined;
    orderId?: number;
}

export interface UserNotificationDTO {
    followUpList?: UserNotificationFollowUpDTO[] | undefined;
    creditNoteList?: UserNotificationCreditNoteDTO[] | undefined;
}

export interface UserNotificationFollowUpDTO {
    userId?: number;
    customerId?: number;
    customerName?: string | undefined;
    phoneNumber?: string | undefined;
    email?: string | undefined;
}

export interface UserType {
    id?: number;
    isActive?: boolean;
    isDeleted?: boolean;
    createdBy?: string | undefined;
    createdDate?: moment.Moment;
    modifiedBy?: string | undefined;
    modifiedDate?: moment.Moment | undefined;
    name?: string | undefined;
    code?: string | undefined;
    description?: string | undefined;
    sortOrder?: number;
}

export interface Vendor {
    id?: number;
    isActive?: boolean;
    isDeleted?: boolean;
    createdBy?: string | undefined;
    createdDate?: moment.Moment;
    modifiedBy?: string | undefined;
    modifiedDate?: moment.Moment | undefined;
    addressLine1?: string | undefined;
    addressLine2?: string | undefined;
    city?: string | undefined;
    state?: string | undefined;
    country?: string | undefined;
    zipCode?: string | undefined;
    phoneNumber?: string | undefined;
    faxNumber?: string | undefined;
    email?: string | undefined;
    latitude?: string | undefined;
    longitude?: string | undefined;
    vendorName?: string | undefined;
    vendorCode?: string | undefined;
    contactName?: string | undefined;
    isCAVendor?: boolean;
    isNVVendor?: boolean;
    caRank?: number;
    nvRank?: number;
    caPercentage?: number;
    nvPercentage?: number;
    cutoffTime?: moment.Moment;
}

export interface VendorCatalog {
    id?: number;
    isActive?: boolean;
    isDeleted?: boolean;
    createdBy?: string | undefined;
    createdDate?: moment.Moment;
    modifiedBy?: string | undefined;
    modifiedDate?: moment.Moment | undefined;
    vendorCode?: string | undefined;
    vendorPartNumber?: string | undefined;
    partsLinkNumber?: string | undefined;
    price?: number;
    onHand?: number;
    cutoffTime?: moment.Moment;
}

export interface VendorOrderDTO {
    id?: number;
    isActive?: boolean;
    isDeleted?: boolean;
    createdBy?: string | undefined;
    createdDate?: moment.Moment;
    modifiedBy?: string | undefined;
    modifiedDate?: moment.Moment | undefined;
    orderId?: number;
    orderDetailId?: number;
    orderNumber?: number;
    purchaseOrderNumber?: string | undefined;
    mainPartsLinkNumber?: string | undefined;
    deliveryMethod?: string | undefined;
    sequence?: string | undefined;
    orderQuantity?: number;
    shipZone?: string | undefined;
    partNumber?: string | undefined;
    vendorPartNumber?: string | undefined;
    vendorPrice?: number;
    partDescription?: string | undefined;
    orderDate?: moment.Moment;
    poDetailStatus?: string | undefined;
    customerName?: string | undefined;
    deliveryDate?: moment.Moment;
    deliveryRoute?: number | undefined;
}

export interface Warehouse {
    id?: number;
    isActive?: boolean;
    isDeleted?: boolean;
    createdBy?: string | undefined;
    createdDate?: moment.Moment;
    modifiedBy?: string | undefined;
    modifiedDate?: moment.Moment | undefined;
    warehouseName?: string | undefined;
    description?: string | undefined;
    notes?: string | undefined;
}

export interface WarehouseLocation {
    id?: number;
    isActive?: boolean;
    isDeleted?: boolean;
    createdBy?: string | undefined;
    createdDate?: moment.Moment;
    modifiedBy?: string | undefined;
    modifiedDate?: moment.Moment | undefined;
    warehouseId?: number;
    warehouse?: Warehouse;
    location?: string | undefined;
    zoning?: number;
    height?: number;
    sequence?: number;
    productId?: number;
    quantity?: number;
}

export interface WarehouseLocationWithStockDTO {
    warehouseLocation?: WarehouseLocation;
    stocks?: Product[] | undefined;
}

export interface WarehousePartDTO {
    warehouseLocationId?: number;
    warehouseStockId?: number;
    productId?: number;
    warehouseId?: number;
    quantity?: number;
    zoning?: number;
    height?: number;
    location?: string | undefined;
    createdBy?: string | undefined;
    createdDate?: moment.Moment;
}

export interface WarehouseStock {
    id?: number;
    isActive?: boolean;
    isDeleted?: boolean;
    createdBy?: string | undefined;
    createdDate?: moment.Moment;
    modifiedBy?: string | undefined;
    modifiedDate?: moment.Moment | undefined;
    productId?: number;
    product?: Product;
    warehouseId?: number;
    warehouse?: Warehouse;
    warehouseLocationId?: number;
    warehouseLocation?: WarehouseLocation;
    quantity?: number;
    location?: string | undefined;
    currentCost?: number;
}

export interface WarehouseStockDTO {
    id?: number;
    isActive?: boolean;
    isDeleted?: boolean;
    createdBy?: string | undefined;
    createdDate?: moment.Moment;
    modifiedBy?: string | undefined;
    modifiedDate?: moment.Moment | undefined;
    warehouseId?: number;
    warehouseLocationId?: number;
    productId?: number;
    quantity?: number;
    location?: string | undefined;
    partNumber?: string | undefined;
    partDescription?: string | undefined;
    destinationWarehouseLocationId?: number | undefined;
    destinationLocation?: string | undefined;
}

export interface WarehouseTracking {
    id?: number;
    isActive?: boolean;
    isDeleted?: boolean;
    createdBy?: string | undefined;
    createdDate?: moment.Moment;
    modifiedBy?: string | undefined;
    modifiedDate?: moment.Moment | undefined;
    orderId?: number;
    order?: Order;
    orderDetailId?: number;
    orderDetail?: OrderDetail;
    status?: string | undefined;
    description?: string | undefined;
    notes?: string | undefined;
}

export interface WeatherForecast {
    date?: moment.Moment;
    temperatureC?: number;
    readonly temperatureF?: number;
    summary?: string | undefined;
}

export interface YearDTO {
    yearNumber?: number;
    year?: string | undefined;
}

export interface Zone {
    id?: number;
    isActive?: boolean;
    isDeleted?: boolean;
    createdBy?: string | undefined;
    createdDate?: moment.Moment;
    modifiedBy?: string | undefined;
    modifiedDate?: moment.Moment | undefined;
    zoneId?: number;
    binCode?: string | undefined;
    zipCode?: string | undefined;
}

export interface ZoneSummary {
    zone?: number;
    numberOfStops?: number;
}